
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Abcd123@

  jpa:

    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.format_sql: true

logging:
  level:
    com.example.authservice: DEBUG
    org.hibernate.type.descriptor: trace

jwt:

